### ISSUE TITLE
[feature request] Per system favorites

### ISSUE THREAD

**Issue by nicosensei** [fgl82/simplemenu#104]
Hi, I'm quite enjoying SimpleMenu on my PocketGo, makes it a really nice low cost device. I have one feature I'd like to request, which would be the abilty to choose betwenn the current, system-agnotic, favorites, and per system favorites. I'm used to per system favorites with EmulationStation from EmuElec, as I tend to have quite a bunch of favorites ;-)

**Comment by fgl82** [comment]
Hello, thanks for your input. I don't think I will be adding this feature soon, first because I don't like it and second because it would add complexity to the code base which, right now, I'm trying to stabilize, removing crashes and leaks.
I will, however, make a note of it and consider it in the future, maybe it's not so complex to implement after all, maybe it's  just a matter of showing only favorites belonging to the section from which someone pressed the favorites button.
That said, I will close this issue and announce the feature, if it ever happens, on the front page of this github.
