### ISSUE TITLE
Doesn't work with RG350P

### ISSUE THREAD

**Issue by DInerenblanc** [fgl82/simplemenu#120]
There's a new RG350 model out and the current offerings aren't compatible with it. Will there be a corresponding update for the RG350P?

**Comment by Panja0** [comment]
I have the same problem.
On stock firmware it crashes back to Gmenu2x.
When using Rogue firmware (v1.7.10) it does work but for other reason I do not want to use Rogue.

Log file entries:
`Mon Aug 10 08:37:17 2020 | INFO  | Processing files
Mon Aug 10 08:37:17 2020 | INFO  | All files loaded
Mon Aug 10 08:37:17 2020 | ERROR | Nice, a critical error!!!`

**Comment by Romstain** [comment]
I also did not manage to run on RG350P

**Comment by DSigmund** [comment]
+1

**Comment by thesush** [comment]
Same here! Using firmware 1.5.1 (compilation date May 21st 2020)
I am trying to dig into this to find the reason but am currently struggling to compile simplemenu (being a newbie with cross-compiling). I have actually managed to compile with the toolchain from this thread: https://boards.dingoonity.org/gcw-development/gcw-zero-toolchain-on-windows-using-wsl/
But here my simplemenu OPK file seems to look for an older libshake.so.0 while libshake.so.1 is actually installed on the RG-350P with firmware 1.5.1.
So in order to proceed here, can anyone you give me a pointer or hint on how to obtain a toolchain which enables compilation for the current 1.5.1 firmware?

**Comment by thesush** [comment]
Ah, and another thing I found out: 5.6.1 works fine with my RG-350P

**Comment by fgl82** [comment]
@thesush I don't own an RG-350P, so I can't fix this. If you ever find the issue, please do submit a pull request with your changes! :)
