### ISSUE TITLE
Not compatible with subfolders in roms directory ?

### ISSUE THREAD

**Issue by Voljega** [fgl82/simplemenu#123]
Hello I wanted to use SimpleMenu on my RG350 and it seems nice.

However I'm using subfolders in most of my roms folders, let's say if my nes roms folder is `/nes`, my nes folder contains these folders : 
```
Action-Adventure
Platform
ShootEmUp
VsFighting
```
and roms inside these folders

Most roms frontend allow in these cases to navigate through fodlers, launch roms from them, get back to parent folders, etc...

However it seems it's impossible to do that with SimpleMenu, it seems I could only put the list of all subfolders in the ini file part for nes, and see their content as flat list, but I'd like to see them as a folder tree, with covers too

Is it possible to do that at all on SimpleMenu and I missed something, or not possible at all ?

**Comment by fgl82** [comment]
@Voljega: yes, this is not possible and won't be, sorry. I'm keeping the flat list as I think it fits better the simplicity of the menu and avoids "rom hoarding" syndrome :)
You can always create a section group for a particular console and add different folders as sections. So instead of console, games and apps, etc. You would have NES, SNES, PCX, etc, and then each of those section groups could have sections that all launch that emulator, but looking at a different rom folder! I hope this is enough for your needs.
