### ISSUE TITLE
Power button to turn off?

### ISSUE THREAD

**Issue by thias** [fgl82/simplemenu#161]
I just updated to the latest version on my RG350M with the new 0A theme, and I'm loving it!

One thing I miss is having the device shutdown just by pressing the power button instead of having to press Start then A to select the shutdown menu entry. Would it be possible to add that to simplemenu? I think that having it be the default behavior, at least when the configured "Session" behavior is "shutdown", would make sense.

**Comment by fgl82** [comment]
So, I wouldn't want it to shut down just by pressing the power button quickly, as that would lead to accidental shutdowns.

Now, with that said, this would mean you would have to long press the power button to get a shutdown dialog to confirm or, if not, just shut down the console, which is already possible by holding the power button, an action that actually does a proper system shutdown.

As you can see, there's no point in implementing a long press shutdown, as it's already available,  and a short press shutdown is out of the question.

What I COULD try to do, is intercept the shutdown signal and display the "shutting down" screen.

Also, if you like this version stay tuned for the next one, it will run better since I've reworked a lot of code.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Matthias Saou ***@***.***>
Sent: Tuesday, April 6, 2021 6:45:36 PM
To: fgl82/simplemenu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fgl82/simplemenu] Power button to turn off? (#161)


I just updated to the latest version on my RG350M with the new 0A theme, and I'm loving it!

One thing I miss is having the device shutdown just by pressing the power button instead of having to press Start then A to select the shutdown menu entry. Would it be possible to add that to simplemenu? I think that having it be the default behavior, at least when the configured "Session" behavior is "shutdown", would make sense.

**Comment by thias** [comment]
Regarding "accidental shutdowns", I think I would also have been worried, if it hadn't been for the RG351 (both P and M) that I've been using with Batocera: Pressing the power button triggers an immediate clean OS shutdown... and I use it all the time, without a single unwanted occurrence so far (it's similarly placed, but on the left). The button is never used for in-emulator action like on the RG350, is it's obviously a lot less prone to user mixup, but it's great to quickly shutdown the device after a frustrating game :sweat_smile: Just save the in-game progress and press the button. Done. Here you'd need to first exit he emulator, but at least you wouldn't be required to enter a menu where you can accidentally change some configuration (just press left or right by mistake, and you'll be rebooting instead of shutting down). Also, accidental shutdown while in simplemenu would have zero consequences, unlike if it was in-game.

I can confirm that pressing the power button for 3 full seconds does seem to trigger a clean shutdown. I know I'm being picky, so feel free to just close this issue if you like, but I don't find it really comfortable to keep that side button pressed for so long, and it feels like you're trying a typical force-shutdown of the device.

Thanks for all your work, looking forward for the next version!

**Comment by fgl82** [comment]
I'm leaving this as it is for now, I've had people report they carry their consoles in their pocket while turned on, so an accidental power press would trigger an unwanted shutdown. I don't think the more accident-prone shutdown solution is worth it, just to save one button press, sorry...
