### ISSUE TITLE
Quits/crashes when pressing select

### ISSUE THREAD

**Issue by docwhat** [fgl82/simplemenu#174]
I just installed 9.3 on my RG350 and it's nice except for one issue:

If I press SELECT it causes SimpleMenu to either quit or crash.  I suspect crash since it doesn't update the `last_state.sav` file.

I found a workaround by pressing B first and then SELECT works as expected.

I'm using Rogue 1.7.10 on the RG350P.

**Comment by fgl82** [comment]
Hi, thanks for reporting this.

Which firmware are you using?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Christian Höltje ***@***.***>
Sent: Friday, July 23, 2021 1:26:14 AM
To: fgl82/simplemenu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fgl82/simplemenu] Quits/crashes when pressing select (#174)


I just installed 9.3 on my RG350 and it's nice except for one issue:

If I press SELECT it causes SimpleMenu to either quit or crash. I suspect crash since it doesn't update the last_state.sav file.

I found a workaround by pressing B first and then SELECT works as expected.

**Comment by materka** [comment]
Same for me.
Using Rogue CFW 1.7.14

**Comment by docwhat** [comment]
> Which firmware are you using?

Stock for the RG350P.  I'll add it to the initial report.

**Comment by fgl82** [comment]
I'm  not supporting stock, just Rogue and Beta

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by docwhat** [comment]
My mistake: I'm using Rogue v1.7.10 -- I forgot I had updated for SimpleMenu.

**Comment by fgl82** [comment]
Ah, good then :)

I'll look into this as soon as I have my rogue device, next week

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by docwhat** [comment]
I just upgraded to Rogue v1.7.14 and the problem is there as well.

**Comment by fgl82** [comment]
Yes, I don't expect the issue to be related to Rogue but to SM, somehow what I fixed before wqs broken again

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by docwhat** [comment]
It's been a while since I've written C code... would your build system allow adding in some kinds of unit tests, like [check](https://libcheck.github.io/check/)?

Seems like it would be a useful way to prevent regressions and test ideas.

**Comment by fgl82** [comment]
I honestly have no idea, C is not the language I'm most familiar with and I had not touched it since college, so you can imagine how much I've forgotten or mnever learned at all.

Regarding test cases, even if there was something to do that, some of the code os tied to things only present on particular devices and has parts that are optionally compiled, so I'm not sure how feasible or useful it would even be.
________________________________

**Comment by docwhat** [comment]
Optionally compiled is okay.  You just put the test in the `#ifdef`s I think.

Specific devices (in an ideal world) are not an issue.  These are unit tests and non-units (e.g. calls to the kernel or another process) are not covered in the concept of "unit tests"... ... ... ...in an ideal world. 😝 

If I have time and spoons, I'll see if I can get a build env setup and take a look at it.

**Comment by fgl82** [comment]
Please verify if this still happens in the latest version

**Comment by fgl82** [comment]
OK, t's been too long, closing this
